packages:
- '.'
extra-deps:
- git: https://github.com/ComputationWithBoundedResources/slogic
  commit: b5f1738b17637923318e793d68fdccb69749a0b8
- git: https://github.com/ComputationWithBoundedResources/term-rewriting-xml
  commit: termcomp2015
- git: https://github.com/ComputationWithBoundedResources/term-rewriting-ext
  commit: a100113b2fb0226de0be5264c07945246f
- git: https://github.com/ComputationWithBoundedResources/tct-core
  commit: 5aba80ab385febb66f7236b99a1acf9db159a9d1
- git: https://github.com/ComputationWithBoundedResources/tct-common
  commit: dbdbddf53b5c62c4c983a8025b7ef388f6f75563
- git: https://github.com/ComputationWithBoundedResources/ara-inference
  commit: ad0f95c533e9031e412aec88f13bd4802ebd02cd
- git: https://github.com/ComputationWithBoundedResources/tct-trs
  commit: termcomp2018
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- multiset-0.2.2
- term-rewriting-0.2
- union-find-array-0.1.0.2
resolver: lts-5.12
allow-newer: true
