packages:
- '.'
extra-deps:
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- multiset-0.2.2
- term-rewriting-0.2
- union-find-array-0.1.0.2
- git: https://github.com/ComputationWithBoundedResources/slogic
  commit: b5f1738b17637923318e793d68fdccb69749a0b8
- git: https://github.com/ComputationWithBoundedResources/term-rewriting-xml
  commit: termcomp2015
- git: https://github.com/ComputationWithBoundedResources/tct-core
  commit: 6704baf6902fe306bd47ade31f1adb1dc001ef4a
- git: https://github.com/ComputationWithBoundedResources/tct-common
  commit: f950378c5ba414f5f02916046ddcb4af4ec6fb19
- git: https://github.com/ComputationWithBoundedResources/tct-trs
  commit: termcomp2016
- git: https://github.com/ComputationWithBoundedResources/tct-its
  commit: 9eb5a4758789f3739e6cb788e468579cfe3ed4d1
resolver: lts-5.12
